### ISSUE TITLE
Design System > Application Shells > Default > UI issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#1149]
**Describe the bug**
Application Shells > Default > UI issue.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Application Shells > Default'

**Actual result-**
Application Shells > Default > UI issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/4acdaab4-b7d0-42db-a6e4-9eca4681c24b)
![image](https://github.com/user-attachments/assets/85a0365e-7a23-4566-96d4-92f7f532176e)
![image](https://github.com/user-attachments/assets/cee59921-ae7b-4201-bd78-b33a94708576)

**Expected result-**
 UI displayed proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/d577502f-0f55-4633-b726-249b4a6b1812)

![Image](https://github.com/user-attachments/assets/afd16f15-2249-491f-8ac3-344c538fa815)

![Image](https://github.com/user-attachments/assets/89fcbf01-d19f-4ae0-902e-8fda6e5048da)

![Image](https://github.com/user-attachments/assets/8e715bf8-249e-4f3f-b527-40078a9160fb)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
![Image](https://github.com/user-attachments/assets/55307b39-58e3-45a7-833a-21306dd4681e)

**Comment by rushigadekarWai** [comment]
Fix on dev

![Image](https://github.com/user-attachments/assets/949454b8-c311-4262-8f09-03a3ce8fa260)

![Image](https://github.com/user-attachments/assets/012a82ea-c185-4c41-bb60-207789eaf555)

![Image](https://github.com/user-attachments/assets/9be546bd-c2c9-43fc-9c1f-449aeb2a3ea1)

![Image](https://github.com/user-attachments/assets/ebde4a41-e1ad-429b-a2aa-05bd0e428e4c)

![Image](https://github.com/user-attachments/assets/9df927c0-28ad-4937-8f71-ba2d73b20266)

![Image](https://github.com/user-attachments/assets/4d9539d0-60d1-4a5b-9860-85eceb6a7521)

![Image](https://github.com/user-attachments/assets/2126b4ea-b1ac-4ffd-8689-4a5aa34c50c6)

**Comment by ketakikotwal** [comment]
Reopen
Error is displayed
![Image](https://github.com/user-attachments/assets/f197bf32-4fc8-4024-bb18-1d9b35c77cff)
![Image](https://github.com/user-attachments/assets/47c364d1-a9c5-408e-9a78-a0b81da95d81)
![Image](https://github.com/user-attachments/assets/132b5b5d-5824-4bbd-878c-b2d6a950ad46)
![Image](https://github.com/user-attachments/assets/9d3b29c2-d278-4832-90cf-574c7f705afe)
![Image](https://github.com/user-attachments/assets/e192feed-568a-4388-94e1-d84e6c8badd8)

**Comment by trivenikulkarni** [comment]
Verified pass on stge
