### ISSUE TITLE
Design System > Elements > Accordion > Docs > Background color is showing to the chevron of first accordion

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#1216]
**Describe the bug**
 Background color is showing to the chevron of first accordion
 
**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/?path=/docs/elements-accordion--docs'
2. Navigate to 'Elements > Accordion > Docs '
 
**Actual result-**
 Background color is showing to the chevron of first accordion

**Screenshots**
![Image](https://github.com/user-attachments/assets/3da6c88b-2c31-4be4-ba13-cd7902d29ec4)

**Expected result-**
 Background color should not show to the chevron of first accordion

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/247bdfef-7877-44c5-8e34-7757a221d52d)

**Comment by ketakikotwal** [comment]
Not Fixed on prod
Background colour is not showing chevron of accordion
![Image](https://github.com/user-attachments/assets/ed4e9287-17c6-4da5-b872-ad0cdc9f16b7)
 But Check
 Hover effect is not applied properly
  ![Image](https://github.com/user-attachments/assets/cac84929-2bfd-4dc1-bbe4-cc70b76199c4)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/08624cf8-7006-4963-8389-ad5ad1316fb0)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/deccaa54-3dbf-437f-9935-b0db22c705a2)
