### ISSUE TITLE
Design System > Elements > Counter > Counter button alignment issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#1226]
**Describe the bug**
 Counter button alignment issue.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/?path=/story/elements-counter--counter'
2. Navigate to 'Design System > Elements > Counter'

**Actual result-**
 Counter button alignment issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/156096ee-d264-41cb-9579-d0322db73472)

Expected -
![image](https://github.com/user-attachments/assets/c4967e97-1287-46b8-9bdd-52bc8805c080)

**Expected result-**
 Counter button alignment should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by RadhikaB123** [comment]
Fixed on staging
![Image](https://github.com/user-attachments/assets/58944af8-d979-4a96-8298-3d8b8eb28135)

**Comment by ketakikotwal** [comment]
not Fixed on Prod
size issue of buttons
![Image](https://github.com/user-attachments/assets/9d611cd6-5b08-4b37-a172-2d91d3d8676e)
In Figma
![Image](https://github.com/user-attachments/assets/0495f1d0-48ab-4236-844d-5e0735186b90)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/ec1c8146-d72f-473e-b88b-bb0a336b3d6f)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/b59f4151-fae8-4279-8f00-cf7e79c93824)
