### ISSUE TITLE
Design system > Side nav bar > Charts and maps are not display in the element section

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#1233]
**Describe the bug**
 Charts and maps are not display in the element section

 
**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/?path=/story/elements-navtabs--icon-only&args=style:Vertical+-Left+Filled'
2. Navigate to 'Side nav bar'
 
**Actual result-**
 Charts and maps are not display in the element section

 
**Screenshots**
![Image](https://github.com/user-attachments/assets/c51a6fd5-f371-4afa-a762-fdb85293bd82)

**Expected result-**
 Charts and maps should display in the element section

**Comment by rameshwarkamandar** [comment]
Fixed on stage 
![Image](https://github.com/user-attachments/assets/41db528b-f200-43a4-bb50-6b481f517271)
![Image](https://github.com/user-attachments/assets/5b93c739-a410-466e-ade5-bedee0224280)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
It display in components section
![Image](https://github.com/user-attachments/assets/7d46b36b-81ef-456d-a7d6-7a032591ae4a)

**Comment by rameshwarkamandar** [comment]
Fixed on dev
![Image](https://github.com/user-attachments/assets/a9712184-30a1-4167-afe2-92d59e742b31)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/94fc786d-9639-41f0-a251-0fe5730be712)
![Image](https://github.com/user-attachments/assets/845db89c-af90-40e1-b309-facd40b123b4)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/9e45cc1a-1110-42aa-8c05-4e097ffad152)
