### ISSUE TITLE
Design System > Components > Webhook Subscription >Default > Required message and alignment issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#1276]
**Describe the bug**
 Required message and alignment issue.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Webhook Subscription >Default'

**Actual result-**
 Required message and alignment issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/6688f409-0157-400b-a981-bd548dfe2069)

**Expected result-**
 Required message and alignment should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by Sachin-Ghorpade** [comment]
@rameshwarkamandar Already fixed this issue in another PR.
PR link for reference: https://github.com/Wai-Technologies/raaghu-react/pull/1299

**Comment by rameshwarkamandar** [comment]
Reopen on stage

![Image](https://github.com/user-attachments/assets/657d2ba5-558a-409a-b8ee-a46f16fac70a)

**Comment by Sachin-Ghorpade** [comment]
Hello @rameshwarkamandar,
The "Add" button alignment issue has already been fixed in Nitin's PR.

**Comment by ketakikotwal** [comment]
not fixed on prod
message alignment issue
![Image](https://github.com/user-attachments/assets/a24c9230-c0e5-4734-8001-b7b9b8eb47dc)

**Comment by ketakikotwal** [comment]
Not fixed on stage
Required message font size is not same
![Image](https://github.com/user-attachments/assets/57a2ae0c-cd64-4975-9824-f2548fe74d83)

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/c35f9ae6-81a9-4ab0-b633-d5a5dbb35277)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/b6fef927-cebe-48c1-8c72-98b2d358b611)
