### ISSUE TITLE
Design System > Component > Top Navigation >Enhancement as per design kit

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1452]
Design System > Component > Top Navigation >Enhancement as per design kit

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/c6b40f09-b974-4236-a29d-b999893f6ac7)

![Image](https://github.com/user-attachments/assets/2d320a1f-8880-4c37-8fa3-0ed55061ada4)

![Image](https://github.com/user-attachments/assets/0023c9fa-a31e-44b7-8b05-7541b0c5cbcd)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
1)Alignment issue
![Image](https://github.com/user-attachments/assets/315a5a8f-dfb3-4cc2-a9e6-ae725ebdc0d5)
In Figma
![Image](https://github.com/user-attachments/assets/b514b9d1-5681-4e72-bdff-23c673fafc72)
2)cross button color and alignment issue
![Image](https://github.com/user-attachments/assets/04b5a281-d76f-4c1f-aacc-42eeaf1707aa)
