### ISSUE TITLE
Design System > Element > Video Player > Enhancement as per design Kit

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1459]
Design System > Element > Video Player > Enhancement as per design Kit

**Comment by RadhikaB123** [comment]
Fixed on staging


![Image](https://github.com/user-attachments/assets/7a74ace1-1b82-493b-954c-9376f50418d3)

**Comment by ketakikotwal** [comment]
Not Fixed on Prod
1)icons alignment issue
![Image](https://github.com/user-attachments/assets/d5717e93-566c-46dc-835f-f008e782c9fa)
![Image](https://github.com/user-attachments/assets/d78247f0-f613-48a3-b060-d045e6492a10)
2)Volume icon opens in wrong direction
![Image](https://github.com/user-attachments/assets/fd216d93-deec-4f73-837e-3d990f383839)
Expected
![Image](https://github.com/user-attachments/assets/f6813e1d-c34c-4378-b222-f2b2ffdbc6ea)
3)In downloaded video circle is little bit different
refer screenshot
![Image](https://github.com/user-attachments/assets/cb60adb4-c4f6-481b-b404-fb962d54c446)
4)There is no cross button or back button if we want not share the video
![Image](https://github.com/user-attachments/assets/351cb6bc-a231-4de7-a514-25b6f195ef73)

**Comment by nitinsonawane123** [comment]
Hello @ketakikotwal, As we are using inbuilt react package for this video player we cannot change the UI. and also we already pass youtube links and vimeo links from there site only. so It it not possible to midify it.
