### ISSUE TITLE
Design System > Element > Checkbox > Enhancement as per design Kit

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1460]
Design System > Element > Checkbox > Enhancement as per design Kit

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/e76be48a-9d5f-40f9-b2ff-74849149d4d5)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
Hover effect does not apply to the Checkbox
![Image](https://github.com/user-attachments/assets/cd5b0863-33c3-4c9f-b585-cf1150c64bb5)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/2b15783f-7414-4b2e-8f1d-f62346a25fc1)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/668d6352-563c-4ae3-908a-2f1b21fecf24)
