### ISSUE TITLE
Design System > Element > Off Canvas > Enhancement as per design Kit

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1471]
Design System > Element > Off Canvas > Enhancement as per design Kit

**Comment by AkshayPotphode** [comment]
Reopen task because i) Buttons are not showing as per the figma design kit. ii) Controls are differant than the figma design kit.

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/08522f16-10d6-407e-aa1e-d7769ba07832)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
Cross button color issue and text is different than figma
![Image](https://github.com/user-attachments/assets/ac550c68-71fb-4e30-beef-9b9727a1ad77)
In Figma
![Image](https://github.com/user-attachments/assets/c7c2e5e4-7d2d-4edc-83ad-735505a2588c)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/1b843a52-5552-40d0-a74b-edbecf833037)

**Comment by ketakikotwal** [comment]
fixed on Prod
![Image](https://github.com/user-attachments/assets/c0b71b08-4a76-4a53-a93c-b2aa77d76497)

**Comment by Sachin-Ghorpade** [comment]
Hello @ketakikotwal  @trivenikulkarni  @RadhikaB123 , 
This is working fine in both the dev and stage environments.
