### ISSUE TITLE
Design System > Elements > Progress Bar > Enhancement as per Figma Design

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1472]
Design System > Elements > Progress Bar > Enhancement as per Figma Design

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/7adfaecf-10a7-4ac6-8e9a-87056a1585fd)

**Comment by ketakikotwal** [comment]
Not Fixed on Prod
In dark mode for error colorvariant it shows primay color
![Image](https://github.com/user-attachments/assets/1ae9ba53-9ce8-4be0-b599-e6923dbedc7d)
In dark mode for circular role error colorvariant doesn't seen
![Image](https://github.com/user-attachments/assets/afbb8564-6a79-49bd-aedb-03a5331ee731)
unable to see in dark mode
![Image](https://github.com/user-attachments/assets/88aefeeb-c9fe-4f36-8641-623f38a67700)
error colorvariant is not applied on dash
![Image](https://github.com/user-attachments/assets/dd09f179-fce8-4301-9018-b61b8e6e92df)
Unable to see primary and error color on block in dark mode and light mode
![Image](https://github.com/user-attachments/assets/9b3dc187-b7c3-4c5c-a29b-2cfc42ca9fa4)
![Image](https://github.com/user-attachments/assets/162163f8-fe48-47b9-97e4-5578756d8d50)
![Image](https://github.com/user-attachments/assets/2f7ca7c4-462a-450f-aa2f-86dbbb7b00d5)

**Comment by rameshwarkamandar** [comment]
Fixed on dev
![Image](https://github.com/user-attachments/assets/7e642434-b7b9-4cfe-9595-cc40d8f12e9c)

![Image](https://github.com/user-attachments/assets/6c52b181-8020-41a9-8200-819f9fec792f)

![Image](https://github.com/user-attachments/assets/d13ea44c-44c8-4464-b711-2a583e6cf267)

![Image](https://github.com/user-attachments/assets/822cc83d-8735-4c4d-976f-08c4387f8daa)

![Image](https://github.com/user-attachments/assets/7fe4cf77-4667-4a45-90c1-e700c60dd9e3)

![Image](https://github.com/user-attachments/assets/678be462-7804-4088-941d-e8a109fad8ac)

![Image](https://github.com/user-attachments/assets/aa853fb0-0f81-4592-86b3-f4e56e233a1b)

**Comment by ketakikotwal** [comment]
not fixed on stage
for error colorvariant all completed steps have not error color
![Image](https://github.com/user-attachments/assets/25e17794-7c92-46be-9ea5-85165e450673)
![Image](https://github.com/user-attachments/assets/42b67fcc-c6c2-407b-9a1e-3ddef5b24dbb)
![Image](https://github.com/user-attachments/assets/97a561ea-ea48-4bea-a96f-00fe5fe111f7)

in figma
![Image](https://github.com/user-attachments/assets/8c020009-203c-4ed9-9e68-49f53157f27d)

**Comment by rameshwarkamandar** [comment]
Resolved issue in this PR https://github.com/Wai-Technologies/raaghu-react/pull/1986

**Comment by rameshwarkamandar** [comment]
Fixed on dev 

![Image](https://github.com/user-attachments/assets/55ef8c2f-9ffb-46e7-89ab-ed9ef5c31243)

![Image](https://github.com/user-attachments/assets/638ae21f-ee63-4a1f-bd7f-63de7cae6d14)

![Image](https://github.com/user-attachments/assets/8fff7d87-c674-4006-b6d2-8aa09d52bb14)

![Image](https://github.com/user-attachments/assets/0d84aa11-2031-4e8b-aedb-2aa880d9af16)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/9d20431b-a4ef-4aa2-bcfc-aecb74d3d1f8)
![Image](https://github.com/user-attachments/assets/8578400c-0374-4da7-a029-546022a9a724)
![Image](https://github.com/user-attachments/assets/9690363d-4155-4880-b92d-87fb89daaabd)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/1ad02999-dd33-44ac-adb7-ecce22a7b774)

![Image](https://github.com/user-attachments/assets/e689a023-0821-4417-894d-72549f7e9e6d)
