### ISSUE TITLE
Design System > Element > Dropdown > Enhancement as per Figma Design Kit

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1491]
Design System > Element > Dropdown > Enhancement as per Figma Design Kit

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/e32b6987-8be5-4b6b-9f00-a81c203546ae)

**Comment by ketakikotwal** [comment]
Not fixed on prod
when click in search box for 2nd time 
![Image](https://github.com/user-attachments/assets/a86a09ca-6950-48d1-85fd-dae3d62afdaa)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/fcc994c7-35d2-482b-b65b-a8cbfcf6b61f)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/93122704-1afd-460b-8bd6-6946769d2019)
