### ISSUE TITLE
Design System > Components > Data Table > Enhancement as per Figma Design

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1511]
Design System > Components > Data Table > Enhancement as per Figma Design

**Comment by Dipak7028** [comment]
### **Css changes** 
**Progress bar change
Badge alignment
Delete icon in center
Add one column is a badge
Change As Per Rameshwar Branch
**

**Screenshots**

![Image](https://github.com/user-attachments/assets/af210c7f-6040-45ab-b791-c9583138973a)

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/1b0804f0-6bf7-4467-8059-7c682d99113c)

**Comment by ketakikotwal** [comment]
Not fixed on prod
![Image](https://github.com/user-attachments/assets/d9e47ecf-84f2-4048-87a7-ea2751373f7a)
In figma
![Image](https://github.com/user-attachments/assets/ea55ba67-f762-4ba0-b07b-d368d44a5c9a)

**Comment by rameshwarkamandar** [comment]
Fixed on dev

![Image](https://github.com/user-attachments/assets/b3f169ee-f19a-4495-aced-08fe3722da28)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/31be1a6b-b165-48ee-97f6-5af470d328cc)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/76290c53-f1ab-442a-a93c-03773bb0de97)
