### ISSUE TITLE
Design System > Elements >Dropdown button > Enhancement as per Figma Design

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1512]
Design System > Elements >Dropdown button > Enhancement as per Figma Design

**Comment by rameshwarkamandar** [comment]
Fixed on stage

![Image](https://github.com/user-attachments/assets/6ecd0492-0965-4746-9b07-808433f9607b)

![Image](https://github.com/user-attachments/assets/0d9ae1ff-7abf-495d-951e-b85089d517c4)

![Image](https://github.com/user-attachments/assets/49c85953-c474-4664-ac2a-f5954d1ce445)

**Comment by ketakikotwal** [comment]
not fixed on Prod
1)Position of tooltip is different than figma
![Image](https://github.com/user-attachments/assets/440d6029-5e8b-4079-8e71-23deed543755)
In Figma
![Image](https://github.com/user-attachments/assets/edcfe6b6-b4d7-434b-98ea-4d138421b847)
2)Button DropdownList  is different from figma
Circle is not proper
![Image](https://github.com/user-attachments/assets/d1faaad0-c819-4275-b06b-d91bfdd966bb)
In Figma
![Image](https://github.com/user-attachments/assets/d55bec67-2edc-4bd3-8469-b4f6a6d0a1dc)
3)Secondary and  Outline Style is same
![Image](https://github.com/user-attachments/assets/937fc604-81bc-4c86-bcc9-f4d49b2fe41c)
![Image](https://github.com/user-attachments/assets/7adffcb4-bfd1-4d5a-930d-eaca36d745f0)
4)for pill shape button transparent style  is not correct
![Image](https://github.com/user-attachments/assets/a771f654-d156-40e8-b16c-6529f30a18d6)

**Comment by rameshwarkamandar** [comment]
"Hello @ketakikotwal and @trivenikulkarni everything is working fine and matches the Figma design. Please review and confirm."

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/e6632e18-0970-49f1-bd63-58d60a7d2d01)

**Comment by ketakikotwal** [comment]
Fixed on Prod

![Image](https://github.com/user-attachments/assets/5d13a82b-968e-4e96-9e00-37fed2e331dc)
