### ISSUE TITLE
Design System > Element > Grid > Enhancement as per Figma Design Kit

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1514]
Design System > Element > Grid > Enhancement as per Figma Design Kit

**Comment by RadhikaB123** [comment]
Fixed on staging



![Image](https://github.com/user-attachments/assets/f97941eb-f6d5-444d-86c8-7b5c5038d6a9)

**Comment by ketakikotwal** [comment]
Not Fixed on Prod
Spelling error
Select All Text is not seen properly
![Image](https://github.com/user-attachments/assets/43da6208-d5e4-41cc-89fa-b811895392c8)
![Image](https://github.com/user-attachments/assets/8c1960d3-606b-41ba-aa78-889df4c95c48)
In figma
![Image](https://github.com/user-attachments/assets/1534281c-a3c2-4e61-8279-e762220a181d)
All functionalities are not completed  yet
![Image](https://github.com/user-attachments/assets/3a4ff0d7-7310-4de2-90f5-a43153d50053)

**Comment by rameshwarkamandar** [comment]
Resolved issue in this PR https://github.com/Wai-Technologies/raaghu-react/pull/1976

**Comment by rameshwarkamandar** [comment]
Resolved issue in this PR https://github.com/Wai-Technologies/raaghu-react/pull/1989

**Comment by rameshwarkamandar** [comment]
Fixed on dev 

![Image](https://github.com/user-attachments/assets/72aa47d5-3aaa-4066-9e55-b52ea600f297)

![Image](https://github.com/user-attachments/assets/c4228727-09e3-4893-b775-449461d04e85)

![Image](https://github.com/user-attachments/assets/f1315457-38fb-4576-83ac-d694afe29698)

![Image](https://github.com/user-attachments/assets/2e79ae69-c1e8-4ed4-961f-a8a32e5b9a05)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/e1041482-6455-4497-8697-3b61416ec35e)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/34f91b33-2ecd-4bf4-bd49-944319430760)
