### ISSUE TITLE
Design System > Elements > Time Picker > Enhancement as per Figma Design

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1519]
Design System > Elements > Time Picker > Enhancement as per Figma Design

**Comment by Abhishek-Shinde-Waiin** [comment]
No changes made as Element was already as per figma. Haven't raised pr for it

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/44204f6d-2453-423d-a18f-e2c3affd5076)

**Comment by ketakikotwal** [comment]
Not fixed on prod
Unable to see settime text in dark theme for light and white colorvariant
![Image](https://github.com/user-attachments/assets/d90da6c6-e50d-47f8-ae01-225a2d16ff3a)
Unable to see texts such as  Set Time ,Cancel, NOW in light theme also for light and white colorvariant
![Image](https://github.com/user-attachments/assets/fa17c3d1-98ca-4ac3-a9de-d4ace2ff188e)
minute dropdown issue
![Image](https://github.com/user-attachments/assets/be94f60e-050a-4ed0-bc22-1cb912249b90)

**Comment by nitinsonawane123** [comment]
Need to check minute dropdown issue.

**Comment by ketakikotwal** [comment]
fixed on staging
![Image](https://github.com/user-attachments/assets/4067b747-7b6a-4241-b914-cd9fdd365134)
![Image](https://github.com/user-attachments/assets/71714b93-387d-4f53-9488-f72dea0ba500)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/955b35dd-efc4-47d5-8328-57c1d5f59717)
![Image](https://github.com/user-attachments/assets/b1ec0c11-e494-4086-a46f-22509f0ecabd)
