### ISSUE TITLE
Design System > Elements > Empty State > Enhancement as per Figma Design

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#1522]
Design System > Elements > Empty State > Enhancement as per Figma Design

**Comment by rameshwarkamandar** [comment]
Fixed on stage

![Image](https://github.com/user-attachments/assets/2a355dba-33e0-4967-a930-2f6242c0762d)

![Image](https://github.com/user-attachments/assets/3f0d24e9-11f3-4570-a28c-797996a90887)

**Comment by ketakikotwal** [comment]
Not Fixed on prod
Empty state texts is little bit different than WF and also Add New Data button is not added here
![Image](https://github.com/user-attachments/assets/68d61e24-df49-47de-a5b5-cdd66a63c227)
In figma
![Image](https://github.com/user-attachments/assets/fea544a6-305e-468e-bd39-67a0d66dd504)

**Comment by rameshwarkamandar** [comment]
Fixed on dev

![Image](https://github.com/user-attachments/assets/f41edddd-c6ad-4654-81f1-64d07858ed9f)

![Image](https://github.com/user-attachments/assets/7c94beb8-b827-4742-974c-7b9f90767e40)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/83bdc1b1-9c1b-4e50-9adf-78edd6530082)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/23f8e1a0-8db9-4725-9e7b-e9334a139bb3)
