### ISSUE TITLE
Design System > Components > Issues identified during Unit Testing of Slider, Text Editor, Tabs, Text Area, Video Player

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1620]
Design System > Components > Issues identified during Unit Testing of Slider, Text Editor, Tabs, Text Area, Video Player

**Comment by supriyartambewaiin** [comment]
Tabs, video player are still pending

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/64afc492-6389-4020-a8d2-c6bbd25204bd)

![Image](https://github.com/user-attachments/assets/51e633d4-f692-4d06-9bee-a4f233745c4a)

![Image](https://github.com/user-attachments/assets/0f9ffbe4-9896-4d3e-9762-fb4a10edfd22)

**Comment by ketakikotwal** [comment]
Not Fixed on Prod
i)Slider
1)Slider dot is not changed according to colorvariants
![Image](https://github.com/user-attachments/assets/24ea1cf1-b83f-457e-bbbf-4230a806d500)
2)In two way slider we didn't get idea about colorvariants means how many percentage active and how many percentage inactive
![Image](https://github.com/user-attachments/assets/2e8cff16-009e-4831-97f6-e9e6a1b0129e)
3)Check tooltip position
![Image](https://github.com/user-attachments/assets/a333c196-67de-494a-8760-d18d0a8553d0)
in Figma
![Image](https://github.com/user-attachments/assets/6b9d636f-5270-479b-af0e-52400f57dc04)

ii)Text Editor
Fixed on Prod
![Image](https://github.com/user-attachments/assets/50b58328-3043-4c89-b041-38277e60d060)

iii)Text Area
Fixed on Prod
![Image](https://github.com/user-attachments/assets/be9d279d-84d0-46aa-bcc5-a85fcd551cf0)

iv)Tab
1)for flap  layout it is different than figma
![Image](https://github.com/user-attachments/assets/da95c25f-c176-400e-992f-abfdc619bedf)
in Figma
![Image](https://github.com/user-attachments/assets/a132ef39-e410-4d8f-9940-076b54b508c3)
2)Unable to see plus icon for selected state
![Image](https://github.com/user-attachments/assets/5c6704d3-c593-4fe9-b2c0-02966cae04cb)
In Figma
![Image](https://github.com/user-attachments/assets/707894f0-b18b-4f71-beea-b7dc9a5412ef)
3)Unable to see Tab in dark mode for hover state and disabled state
![Image](https://github.com/user-attachments/assets/c8421a2d-1a14-4d3c-93ae-e39729460940)
![Image](https://github.com/user-attachments/assets/0d9055b1-37bd-49f5-a4cd-21abd6675a56)

vi)video player
found some issues in video player. added screenshots in other video player task

**Comment by ketakikotwal** [comment]
1)Slider-not fixed on stage
 check tooltip position 
![Image](https://github.com/user-attachments/assets/8b0d9f9d-0081-4a51-830c-93bfdf9a3e72)
2)Text Editor-fixed on stage
![Image](https://github.com/user-attachments/assets/f6350b6b-5861-4e29-946d-e0d18e7b7422)
3)Text Area-fixed on stage
![Image](https://github.com/user-attachments/assets/666a556c-a77b-4a27-8ceb-800cdb2dc3bf)
4)Tab-not fixed stage
![Image](https://github.com/user-attachments/assets/4c496c69-d270-4b5e-9d5e-670af8a6d174)
5)Check for hover and disabled state
![Image](https://github.com/user-attachments/assets/4354bd4e-5a34-4f34-8a15-910763680db8)
![Image](https://github.com/user-attachments/assets/19059cbc-8f08-418f-bed0-066e9046a5e0)

**Comment by nitinsonawane123** [comment]
Need to check tooltip position

**Comment by ketakikotwal** [comment]
![Image](https://github.com/user-attachments/assets/0102ab53-d3e3-4b05-919d-e789082318bf)
![Image](https://github.com/user-attachments/assets/a00d303a-efff-4708-9173-9b7f38b8fc6d)
![Image](https://github.com/user-attachments/assets/0b3faea5-6481-47b2-9840-e140d1284ec4)
![Image](https://github.com/user-attachments/assets/3b8265a0-027f-4260-9d07-222738f15d0e)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/1ac51d3c-b87a-44e5-86b4-f1c4948f1f4e)

![Image](https://github.com/user-attachments/assets/ccfaedef-33d3-44ce-b4dc-530f4157e777)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/c461718f-10d1-417a-8a58-ed1a99d99b7f)
![Image](https://github.com/user-attachments/assets/67895605-05f8-466f-813f-bbc5c0155071)
