### ISSUE TITLE
Design System > Component > Create new component Prompt Enhancer as per design [Chat] [New Design]

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1689]
Design System > Component > Create new component Prompt Enhancer as per design [Chat]

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/0ad0245f-73b3-433b-b217-545f0ad00448)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
1)Lines are not connected properly
![Image](https://github.com/user-attachments/assets/22eb3f54-cf23-4dfd-886d-4f00b3fd3d5f)
2)Alignment issue and size issue
![Image](https://github.com/user-attachments/assets/ce2a4cd9-5b89-4bc6-9a31-70b0afcd42b4)
In Figma
![Image](https://github.com/user-attachments/assets/d0d64934-992f-4d92-9843-db0ad01c2319)

**Comment by supriyartambewaiin** [comment]
Hello @ketakikotwal and @trivenikulkarni,
After latest deployment on prod UI has been changed so this bug is not valid
