### ISSUE TITLE
Design System > Component > Create new component Side Bar as per design [Chat]

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1701]
Design System > Component > Create new component Side Bar as per design [Chat]

**Comment by rameshwarkamandar** [comment]
Top margin issue

![Image](https://github.com/user-attachments/assets/0091bbc9-d186-40ce-8606-94f926b7d790)

**Comment by rameshwarkamandar** [comment]
Fixed on dev

![Image](https://github.com/user-attachments/assets/82ad6b29-525a-4d37-9f3d-649806d2a3a1)

**Comment by ketakikotwal** [comment]
not fixed on stage
side bar is not according to figma
![Image](https://github.com/user-attachments/assets/87072801-f123-45d0-927b-b8e1f54a71ba)
in Figma
![Image](https://github.com/user-attachments/assets/7a71da72-1e3f-4aec-b920-7ac9dc9713d3)

**Comment by rameshwarkamandar** [comment]
Fixed on dev

![Image](https://github.com/user-attachments/assets/9924f7cb-b60a-42fa-b191-06ba7ada031a)

![Image](https://github.com/user-attachments/assets/7d9d1a56-943b-4cd3-925f-fa312f7ff040)

**Comment by ketakikotwal** [comment]
Not fixed on stage
Hover effect is not applied sidebar icons
![image](https://github.com/user-attachments/assets/2df5b123-5103-44b6-b831-40728c57a25e)
In Figma
![image](https://github.com/user-attachments/assets/e1abe67b-bfd4-4b94-8aea-a8992babc5e3)

**Comment by rameshwarkamandar** [comment]
Fixed on dev

![Image](https://github.com/user-attachments/assets/6f39b519-4f94-4b45-ae16-b6422138aedd)

![Image](https://github.com/user-attachments/assets/3932a915-e949-4a96-b5fb-39fd723e1120)

![Image](https://github.com/user-attachments/assets/807da8c1-6bfe-4205-b2ff-25ad99361d24)

**Comment by ketakikotwal** [comment]
Not fixed on stage
Check tooltip position
![Image](https://github.com/user-attachments/assets/5a5bd94c-b91a-48b0-8866-f78c4e6d6597)
![Image](https://github.com/user-attachments/assets/337b2de2-e226-4c82-9b84-2b9532a1f179)

In Figma-Tooltip position
![Image](https://github.com/user-attachments/assets/8c522ff6-fb1d-4ab3-893b-ee45597a003e)
![Image](https://github.com/user-attachments/assets/38da4482-8623-4af4-a44c-ec4525253061)

**Comment by rameshwarkamandar** [comment]
Hello @ketakikotwal & @trivenikulkarni,

In the collapsed state, when the text is long, the tooltip appears on the right side. For shorter text, the tooltip appears at the bottom.

Please refer to the Bootstrap tooltip for reference.

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/2fd644c7-81c7-4b5b-bfdf-2f0e4c190c1c)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/57f4984a-8905-4ede-9ef8-254792ac7b09)
