### ISSUE TITLE
Storybook > Component > Account > Default > Captcha > Issues on Account component Small, Large mobile view captcha not visible.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#172]

**Comment by rameshwarkamandar** [comment]
**Describe the bug**
Issues on Account component Reqiured message is not display.
Small, Large mobile view captcha not visible.

**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/?path=/story/components-account--default'
2. Navigate to 'Storybook > Component > Account > Default > Captcha '

**Actual result-**
Issues on Account component Reqiured message is not display.
Small, Large mobile view captcha not visible.

**Screenshots**
![image](https://github.com/user-attachments/assets/17546d21-0870-41f9-b862-588509153a4e)

![image](https://github.com/user-attachments/assets/482396bb-1903-4341-80fa-2c9594959fe0)

**Expected result-**
Issues on Account component Reqiured message should be display.
Small, Large mobile view captcha should be display.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by rameshwarkamandar** [comment]
Clickable button mouse hover text is not display.
After submitting Version field is not clear and required message still visible.
Small, Large mobile view captcha should be display.

![Image](https://github.com/user-attachments/assets/4c7b7fd0-093a-4db3-8121-757f7a1afa93)

![Image](https://github.com/user-attachments/assets/45c0dfee-7a70-4191-8773-762b89b47c3b)

![Image](https://github.com/user-attachments/assets/f7491d52-8aca-49ed-aac0-f6957683c013)

**Comment by rameshwarkamandar** [comment]
Version alignment issue both version dev / stage
![Image](https://github.com/user-attachments/assets/0750b634-73b4-4a41-b39c-c7b7633d6962)

**Comment by poojagurav21** [comment]
@rameshwarkamandar  Fixed in the pull request :https://github.com/Wai-Technologies/raaghu-react/pull/955

**Comment by rameshwarkamandar** [comment]
Fixed on stage /dev
![Image](https://github.com/user-attachments/assets/09c2ff5b-1967-42e7-aaad-37cd13bedaa0)

**Comment by rameshwarkamandar** [comment]
Issue still exist on stage/ dev 
Small, Large mobile view captcha not visible.
![Image](https://github.com/user-attachments/assets/0cd7f857-8b32-4c95-9de2-455bb0fe3cc7)

**Comment by rameshwarkamandar** [comment]
Fixed on dev
![Image](https://github.com/user-attachments/assets/6d6653e9-cb03-4142-aeab-67d17e0a843d)

![Image](https://github.com/user-attachments/assets/581d671d-e7ab-4d1f-9cb0-c2837d363757)

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![image](https://github.com/user-attachments/assets/1b084b8c-e86e-4928-91d2-cc8b5b465619)
![image](https://github.com/user-attachments/assets/333bc72b-bae7-40e8-80a4-f07e3feff69d)
![image](https://github.com/user-attachments/assets/15916cef-c413-4b60-8f6d-4c0199675a37)
