### ISSUE TITLE
Design system > Components >Feed >Alignment issue of thumb

### ISSUE THREAD

**Issue by ketakikotwal** [Wai-Technologies/raaghu-react#1756]
**Describe a Bug**
Alignment issue

**Steps to Reproduce a Bug**
1.Login to https://stage-react.raaghu.ai/?path=/story/components-feed--review-feed
2.Navigate Elements > Feed
3.Check Alignment

**Actual Result**
![Image](https://github.com/user-attachments/assets/e2eea92d-be93-4e5f-a101-a78f7170129d)

**Expected Result**
Alignment should be proper

**Comment by RadhikaB123** [comment]
Fixed on staging

![Image](https://github.com/user-attachments/assets/09c414c0-b123-4308-95ca-6feb85424ff9)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
![Image](https://github.com/user-attachments/assets/9347550d-38e0-4f2a-ad1a-9d55aeccfa01)

**Comment by supriyartambewaiin** [comment]
@ketakikotwal, It is already fix and shown it to @RadhikaB123.

CC : @trivenikulkarni 

![Image](https://github.com/user-attachments/assets/c3b3ed50-ecf1-4f3c-a408-e37f028196ef)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/f0ad41b5-094a-4e31-8f96-4b2d7bdc65e5)
