### ISSUE TITLE
Design system > Components >Features > Alignment and mobile view issues

### ISSUE THREAD

**Issue by ketakikotwal** [Wai-Technologies/raaghu-react#1790]
**Bug 1**
**Describe a Bug**
Alignment issue
Full page is not displaying in small as well as large mobile views

**Steps to Reproduce a Bug**
1. Login to https://stage-react.raaghu.ai/?path=/story/components-features--default
2. Navigate Components > Features > 
3. Verify alignment
4.Check page in small and large mobile views

**Actual Result**
![Image](https://github.com/user-attachments/assets/32ab8e93-d790-4ca3-9f2f-e63b15a73539)
![Image](https://github.com/user-attachments/assets/bb6866bc-f227-431e-8eae-9d1189837a58)
![Image](https://github.com/user-attachments/assets/8a0140d8-b235-438d-83d5-55de324b7cd3)

**Expected Result**
Alignment should be proper
Page should be displayed in all mobiles

**Comment by ketakikotwal** [comment]
Not fixed on stage
![Image](https://github.com/user-attachments/assets/ef9eb175-3b51-4f84-b0cb-f492ccb78716)
Full page is not display
![Image](https://github.com/user-attachments/assets/e0e9a228-927f-449a-9bad-103e509f8133)

**Comment by Dipak7028** [comment]
fixed on dev

**Comment by RadhikaB123** [comment]
Fixed on stage

![Image](https://github.com/user-attachments/assets/b070aa3a-de38-491e-8c0e-d27ce15ee1f3)

![Image](https://github.com/user-attachments/assets/9c22dabf-209e-4f3b-9d54-62b5d91f5069)

**Comment by ketakikotwal** [comment]
not fixed on Prod
![Image](https://github.com/user-attachments/assets/72a6335b-298e-4180-98ea-2f39dac0898f)

**Comment by Dipak7028** [comment]
fixed on dev and stage
![Image](https://github.com/user-attachments/assets/8b037d54-edf6-4897-8752-bbfc8eaf1169)

**Comment by ketakikotwal** [comment]
It Fixed on stage but
![Image](https://github.com/user-attachments/assets/39f202be-da83-4fbc-b548-158dea9c1224)
It not fixed
tagging is not seen there
![Image](https://github.com/user-attachments/assets/f1409302-3a06-4dc6-913a-ef13bdf42929)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/748e92e7-71cc-4b03-8e23-40d38e5a3af3)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/c0c24a9f-a2d5-4797-916d-c1234e444df0)
![Image](https://github.com/user-attachments/assets/2b33a947-32df-4ce8-b4cd-b6e4e474e3bf)
