### ISSUE TITLE
Design System > Element > Typing Section > Enhancement as per new design

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1982]
Design System > Element > Typing Section > Enhancement as per new design

![Image](https://github.com/user-attachments/assets/8e423a94-3478-4ad2-a8f9-39f5a4717447)

**Comment by ketakikotwal** [comment]
not fixed on stage
![Image](https://github.com/user-attachments/assets/cce9e50d-68fe-47a1-b943-27bd12a68620)
Expected
![Image](https://github.com/user-attachments/assets/db6158a2-d22d-4d5d-9ff2-b5b705adc6d0)

**Comment by rameshwarkamandar** [comment]
Fixed on dev 
![Image](https://github.com/user-attachments/assets/91da2825-40f9-4f5f-aeca-da4be63b06c0)

![Image](https://github.com/user-attachments/assets/e8803300-dfc7-4cba-a8fd-4eeeec041516)

![Image](https://github.com/user-attachments/assets/ff3c4948-14c2-41fb-bfa0-8e0b19bf58bb)

![Image](https://github.com/user-attachments/assets/65312cd6-612b-4533-8d17-75e1609d0e0b) 

![Image](https://github.com/user-attachments/assets/f1ea0848-ab38-48cc-9be2-b5e9f06fd3ea)

**Comment by RadhikaB123** [comment]
Reopen on staging
Only dropdown is display in dark mode
![Image](https://github.com/user-attachments/assets/3a2a9910-4ecf-4b0b-bf4e-49e0fc320636)

![Image](https://github.com/user-attachments/assets/e6e2bcae-aee6-483b-a380-7ea99cbdf330)

**Comment by rameshwarkamandar** [comment]
Fixed on dev

![Image](https://github.com/user-attachments/assets/d3a7b97f-a779-4880-91ae-df2ee3731cb6)

![Image](https://github.com/user-attachments/assets/4e9c0c7e-a6de-42cb-892d-bcd9b5eaf196)

**Comment by ketakikotwal** [comment]
Need to create design in dark mode for typing section element
Not fixed on stage
only dropdown is display in dark mode
![Image](https://github.com/user-attachments/assets/b85c4a3a-8803-42a7-8c24-f3cd0b199814)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/a4eaa7d8-19e1-4dd7-8d27-76e42d7e4ffc)
