### ISSUE TITLE
Design System > Read Me File > 3 links needs to remove

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#2064]
Design System > Read Me File > 3 links needs to remove 

**Steps** 
1. Open read me file https://github.com/Wai-Technologies/raaghu-react?tab=readme-ov-file#learn-more
2.Click on below 3 links

**Actual Result**
3 links are not redirecting to any appropriate content

**Expected Result**
Bellow highlighted links needs to remove
![Image](https://github.com/user-attachments/assets/10c112ad-f6c9-4fc0-bc2e-12c12127680d)

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/67525fde-b25e-47a9-9101-91a81c2950fe)

**Comment by ketakikotwal** [comment]
Not fixed on prod
![Image](https://github.com/user-attachments/assets/88726260-6302-4b94-ac5a-76b322d5f3f7)

**Comment by trivenikulkarni** [comment]
Not fixed on production

![Image](https://github.com/user-attachments/assets/915e058c-d591-4ef1-a855-6a710c00f9d8)
