### ISSUE TITLE
Design System > Component > Bank Card Details  > The 'Set as Default' and 'Edit' options are not vertically aligned with the title.

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#2250]
Design System > In the Bank Card Details component, the 'Set as Default' and 'Edit' options are not vertically aligned with the title.

**Comment by Piyush-Joshi-WaiTech** [comment]
Fixed on dev

**Comment by trivenikulkarni** [comment]
<img width="1544" height="697" alt="Image" src="https://github.com/user-attachments/assets/a027c7e3-9527-4e71-950e-71714a37afcb" />

**Comment by Piyush-Joshi-WaiTech** [comment]
Fixed on dev:

<img width="1919" height="994" alt="Image" src="https://github.com/user-attachments/assets/8419d903-fb86-49a3-94b8-d98d67fe178a" />

**Comment by trivenikulkarni** [comment]
Still not aligned on stage

<img width="1544" height="672" alt="Image" src="https://github.com/user-attachments/assets/1580b27c-116a-4950-87a4-e925aace2d47" />

**Comment by Piyush-Joshi-WaiTech** [comment]
On staging, the bank card details are aligned vertically as expected. Here is the screenshot:

<img width="1920" height="1038" alt="Image" src="https://github.com/user-attachments/assets/90d2ecad-8bbc-4ba8-b855-7f6f560784d1" />
