### ISSUE TITLE
Storybook > Application Shells > Header >Add Layout Here is not display full screen.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#695]
**Describe the bug**
1. Add Layout Here is not display full screen.
2. Small and large Mobile view alignment issue for Chevron and dropdown.

**Steps to reproduce bug**
1.Go to 'https://stage.raaghu.ai/'
2. Navigate to 'Storybook > Application Shells > Header'

**Actual result-**
1. Add Layout Here is not display full screen.
2. Small and large Mobile view alignment issue for Chevron and dropdown.

**Screenshots**
![image](https://github.com/user-attachments/assets/c018dad0-78f8-4b75-af6c-ae18142b359c)

![image](https://github.com/user-attachments/assets/f6cd03ef-e0c7-4be3-b92f-1d52b0cec58a)

![image](https://github.com/user-attachments/assets/2e98ca2e-521f-47f1-ae4a-b790aa8f6a89)

**Expected result-**
1. Add Layout Here should be full screen.
2. Small and large Mobile view alignment should be proper for chevron and dropdown.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by prakashmhaske** [comment]
Hello @rameshwarkamandar I have did above changes


![image](https://github.com/user-attachments/assets/09a6f07d-4170-4686-b33b-9feba80e20bc)
![image](https://github.com/user-attachments/assets/8546c2e6-8394-4f4c-85a8-d786dd50f465)
![image](https://github.com/user-attachments/assets/04afef31-0b0a-45b0-985a-a4475a4bf250)

**Comment by RadhikaB123** [comment]
Fixed on staging
![Image](https://github.com/user-attachments/assets/69cd44e8-9452-4217-979d-c74c98a701b5)
![Image](https://github.com/user-attachments/assets/a3c22d4a-acfe-47d3-b790-c447b8e57516)
![Image](https://github.com/user-attachments/assets/4dd454a1-ab22-4686-907a-8b8a3f4e89b8)

**Comment by rameshwarkamandar** [comment]
Issue still exists on stage/ dev

![Image](https://github.com/user-attachments/assets/e6d2fb26-5924-4c10-b39b-32ccdcd817c5)
![Image](https://github.com/user-attachments/assets/8a4164eb-3073-4c0a-971b-dda294f469b7)

![Image](https://github.com/user-attachments/assets/c4ff96ae-7694-4725-96d4-2c10440e5cac)

**Comment by rameshwarkamandar** [comment]
Fixed on dev
![Image](https://github.com/user-attachments/assets/3ca42015-e9a4-4b2a-a6ce-a13542788263)
![Image](https://github.com/user-attachments/assets/612da891-41af-454d-b64a-b856859c6742)

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![image](https://github.com/user-attachments/assets/d931b15d-a9e9-4541-ad3e-1aeb31786ee3)
![image](https://github.com/user-attachments/assets/d53d2607-8bd4-4f84-a41b-b6fd2b0d25eb)
