### ISSUE TITLE
Design System > Elements > Card : Minor Issues

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#753]
Design System > Elements > Card : Minor Issues
Docs	1]  Cards developement different than design
Default	2] Three styles are missing
	3] Hover and  selected states are missing

**Comment by rameshwarkamandar** [comment]
1. Alignment issue link button all stories.
2. Text is different all stories.

![image](https://github.com/user-attachments/assets/fffd6733-bdc1-451c-a542-e1642ec7c0a8)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/c0375757-5ccb-4b18-96a3-8f5c1ca5795c)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
Hover effect and selected effect is same here
![Image](https://github.com/user-attachments/assets/1beebdb3-1f2b-4799-bcca-836f43c3da82)
![Image](https://github.com/user-attachments/assets/d7de75da-7a31-4ef2-bc2f-b790b1dc1fd8)
