### ISSUE TITLE
Design System > Create new component for Chatbot

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#759]
Design System > Create new component for Chatbot
![image](https://github.com/user-attachments/assets/836a63e2-f3b9-4419-8ee9-fbef1208f06c)

**Comment by suchithravipin1991** [comment]
![Image](https://github.com/user-attachments/assets/b2afe4ce-cb41-489e-879c-c9553766a0bb)

**Comment by suchithravipin1991** [comment]
The Chat component is designed to facilitate a user commenting system similar to chat interfaces. Key functionalities include:

User Comments Display:
Displays a list of comments made by users, including their names, profile pictures, timestamps, and content (text and images).

Current User Identification:
Differentiates between comments made by the current user and other users, adjusting the layout accordingly for better visual context.

Emoji Picker Integration:
Provides an option for users to add emojis to their comments through an integrated emoji picker.(Additional component creation required, for now keep this value false)

Image Upload Support:
Allows users to upload images to their comments. Only image files are accepted, and the uploaded image is displayed within the comment.

Comment Deletion:
If enabled, allows users to delete their comments, with appropriate UI feedback for the deletion action.

Dynamic Date Formatting:
Formats comment timestamps according to a specified date format (e.g., mm/dd/yyyy, dd/mm/yyyy, mm/dd/yyyy with time).

Comment Count Tracking:
The parent component can access the current count of comments through a callback, allowing for state management and UI updates in the parent context.

Responsive Design:
The component is styled to be responsive, ensuring usability across different devices and screen sizes.

**Comment by suchithravipin1991** [comment]
Requirements Changes :  
1.Switch the positions of comments made by the current user and those made by other users to enhance user experience.
2. Fix the time span for the delete option, allowing users to delete their comments only within a specified timeframe after posting.
3. Implement dynamic background color changes for comments based on their status or criteria to improve visual differentiation.

**Comment by rameshwarkamandar** [comment]
Raname Chat = Chatbot
allow Delete & date Format Control are not working.
Remove information icon as per above commented image.
Input box display square Expected as rounded as per above commented image.
![Image](https://github.com/user-attachments/assets/cb79e268-8bd6-4101-bcf7-bef9e779c7b9)
![Image](https://github.com/user-attachments/assets/236a9ee2-ddcd-450d-881c-33dc59ab7cf8)

**Comment by rameshwarkamandar** [comment]
Icon is out of input box.
![Image](https://github.com/user-attachments/assets/66487748-3dec-4185-b041-617c6de1b931)

![Image](https://github.com/user-attachments/assets/95de0b14-0ee2-4ec9-ab41-9f8cdd6830e1)

**Comment by abhijeetjawale1** [comment]
working fine on dev and stagging icon is visible inside the input box 
![Image](https://github.com/user-attachments/assets/23f3c248-77fb-477b-a245-230d2131f6a5)

![Image](https://github.com/user-attachments/assets/b49c6008-1412-4f3d-9d9c-ccc0d1a641c0)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/b3dc5ee1-284d-46cb-99e3-ca9d7fe9f8e3)

**Comment by ketakikotwal** [comment]
Not fixed on Prod
![Image](https://github.com/user-attachments/assets/8d6f45ea-392b-4685-8adc-9cbf84598aa2)
1)uploader and emoji size icon issue
in figma
![Image](https://github.com/user-attachments/assets/b4691b47-6df5-4533-881a-0098a5924a2b)
2)Chat sending issue
The Enter key on the keyboard should work there for sending chat
3)can't delete entered chat

**Comment by ketakikotwal** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/aff6fce0-8405-4cb8-a76d-43dcc4536ab0)

**Comment by RadhikaB123** [comment]
Fixed on prod

![Image](https://github.com/user-attachments/assets/d0b4e346-2c5d-4fb8-a962-357c472fa1ab)

**Comment by ketakikotwal** [comment]
Fixed on Prod
![Image](https://github.com/user-attachments/assets/2e889c10-6e74-434a-ae9e-9a339f0601a8)
