### ISSUE TITLE
Design System > Version 8.3 > Component > Datatable > Action button on Left side > Not able to see the 'Edit' option after hovering over the row below in the table

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#810]
**Describe the bug**
Not able to see the 'Edit' option after hovering over the row below in the table
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/components-datatable--action-button-on-left-side'
2. Navigate to ' Component > Datatable > Action button on Left side '
 
**Actual result-**
Not able to see the 'Edit' option after hovering over the row below in the table
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/7ef373d0-7183-4356-8688-ca184b764c5e)

 
**Expected result-**
'Edit' option should show after hovering over the row below in the table

**Comment by hemalatagaikwad** [comment]
@RadhikaB123  @VenuKG   this bug is  reproduced on dev and stage.
@VenuKG  Please do changes on dev branch also.

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![image](https://github.com/user-attachments/assets/1e5ac14a-69af-4a05-8874-12383356b4a5)
Fixed on dev
![image](https://github.com/user-attachments/assets/66068e95-412b-4f7a-a2a5-9aeeb50483da)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/a7f36e35-ecba-4a5c-997f-8ed69c2f47b5)

**Comment by ketakikotwal** [comment]
not fixed on Prod
![Image](https://github.com/user-attachments/assets/67480787-6f84-4da3-9073-0894337872a1)
