### ISSUE TITLE
Design System > Components > My Settings > Default > Error message alignment issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#845]
**Describe the bug**
1. My Settings > Default > Error message alignment issue.
2. Apply for position.
3. Developer Mode

**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > My Settings > Default'

**Actual result-**
1. My Settings > Default > Error message alignment issue.
2. Apply for position.
3. Developer Mode

**Screenshots**
![image](https://github.com/user-attachments/assets/dea20359-db47-4da8-88a4-65c48c2faf8c)
![image](https://github.com/user-attachments/assets/ebc7da19-9456-4010-9486-2335bfd998f1)
![image](https://github.com/user-attachments/assets/c3c2faa3-192d-40b5-b491-8d8e18ac2a32)

**Expected result-**
1. My Settings > Default > Error message should be align properly.
2. Apply for position.
3. Developer Mode

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by poojagurav21** [comment]
@rameshwarkamandar After merging the changes of Resolved Bug 660 : Storybook > Components > Change Password > Default > Error Message Alignment Issue #839 pull request this issue will be fixed .

Refer Bug [660 : Storybook > Components > Change Password > Default > Error Message Alignment Issue](https://github.com/orgs/Wai-Technologies/projects/16/views/1?filterQuery=assignee%3A%40me&pane=issue&itemId=79514582&issue=Wai-Technologies%7Craaghu-react%7C660)
Pull request: https://github.com/Wai-Technologies/raaghu-react/pull/839/files

**Comment by rameshwarkamandar** [comment]
Fixed on stage/dev

![Image](https://github.com/user-attachments/assets/81d4581a-ed07-4085-b1aa-9a33eacf04aa)
![Image](https://github.com/user-attachments/assets/4f0a50a7-3ab6-4581-a092-42ff55390f89)
![Image](https://github.com/user-attachments/assets/205d50d1-1ac9-422d-979b-e0001cd5fd78)
![Image](https://github.com/user-attachments/assets/24007ef0-b653-481d-acc4-493ec10bae95)

![Image](https://github.com/user-attachments/assets/efcf310b-8736-42b3-b489-b07237bfc7c4)
![Image](https://github.com/user-attachments/assets/c9c93cef-a942-4aa4-84c9-f0f04447904b)

**Comment by rameshwarkamandar** [comment]
Input box, label, file uploader alignment issue.
![Image](https://github.com/user-attachments/assets/8e9916dc-f3f7-41fa-8323-7330890f7de8)

Expected -
![Image](https://github.com/user-attachments/assets/f845bcd1-ab7e-4ac6-8df3-59e8fb3cd207)

**Comment by rameshwarkamandar** [comment]
File uploader alignment issue
![Image](https://github.com/user-attachments/assets/5a5c7bef-dca6-4929-be95-3dee7cef2cf1)

**Comment by rameshwarkamandar** [comment]
Issue still exists ion stage
![image](https://github.com/user-attachments/assets/55475c5b-dd1b-47b2-941a-4711c20124f1)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/5830c1b3-bbeb-49be-acce-78542985eb7b)

**Comment by rameshwarkamandar** [comment]
Alignment Issue still exists on stage
![image](https://github.com/user-attachments/assets/1601fd4d-92a2-4b80-9ca8-5ecc8a783770)

![image](https://github.com/user-attachments/assets/509ef710-bdae-4e7f-aaa6-01afbffff7eb)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/e9948e28-46be-44d7-9918-6c8d4dad026d)
![image](https://github.com/user-attachments/assets/6edea0de-947f-4fec-a447-32c40cb127b4)
